### ISSUE TITLE
ESP32-C6

### ISSUE THREAD

**Issue by michcfr** [mercenaruss/uzg-firmware#17]
Hello,
I would be interested to adapt the uzg-firmware for the ESP32-C6 that already integrates a ZigBee radio. So no need of the CC2652P.
What part of the code should I change/adapt?
thank you

**Comment by xyzroe** [comment]
Hello. Sounds great. As I know C6 don't support WiFi and Zigbee at the same time. But if don't need WiFi it's ok. 
So: first you need to convert this project from using PlatformIO to ESP-IDF, because C6 with Zigbee didn't supported by PlatformIO, than you need to rewrite that part of code that just send TCP data to CC2652 to parse this data and take actions corresponding to these commands, also isame thing in the opposite direction. Also you need to write all Zigbee coordinator related actions. I thinks it will looks something like that.
